allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true

source-item-ordering = ["module"]
module-items-ordered-within-groupings = []
module-item-order-groupings = [
  ["modules", ["extern_crate", "mod", "foreign_mod"]],
  ["imports", ["use"]],
  [
    "declarations",
    [
      "macro",
      "global_asm",
      "static",
      "const",
      "ty_alias",
      "enum",
      "struct",
      "union",
      "trait",
      "trait_alias",
      "impl",
    ],
  ],
  ["implementations", ["fn"]],
]
